""" removed unique constraint from vualt model

Revision ID: 33e8230ed8b3
Revises: 83780a9b0b2a
Create Date: 2025-09-13 12:41:14.784085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e8230ed8b3'
down_revision: Union[str, Sequence[str], None] = '83780a9b0b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vault_name_key'), 'vault', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('vault_name_key'), 'vault', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
