"""otp secret nullable

Revision ID: 345e714ee204
Revises: fe063159fbdf
Create Date: 2025-10-06 13:06:47.476253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345e714ee204'
down_revision: Union[str, Sequence[str], None] = 'fe063159fbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'otp_secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'otp_secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
