"""added stuff for 2fa into user model

Revision ID: a8a30a4af065
Revises: 1a75c8f3c26a
Create Date: 2025-09-14 17:12:22.896186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a30a4af065'
down_revision: Union[str, Sequence[str], None] = '1a75c8f3c26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('otp_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_secret')
    op.drop_column('user', 'mfa_enabled')
    # ### end Alembic commands ###
