"""fixed enum made it naative enum false to avoid enum mistakes ffs

Revision ID: de7fbd2ad16d
Revises: 240e6f7e12ce
Create Date: 2025-10-14 11:52:18.406373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de7fbd2ad16d'
down_revision: Union[str, Sequence[str], None] = '240e6f7e12ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secret', 'type',
               existing_type=postgresql.ENUM('CREDENTIAL', 'NOTE', 'DOCUMENT', 'creditcard', name='secrettype'),
               type_=sa.Enum('credential', 'note', 'creditcard', name='secrettype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secret', 'type',
               existing_type=sa.Enum('credential', 'note', 'creditcard', name='secrettype', native_enum=False),
               type_=postgresql.ENUM('CREDENTIAL', 'NOTE', 'DOCUMENT', 'creditcard', name='secrettype'),
               existing_nullable=False)
    # ### end Alembic commands ###
