"""added secret model

Revision ID: df7c5781454a
Revises: effc208c0d2c
Create Date: 2025-09-08 06:25:50.543722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df7c5781454a'
down_revision: Union[str, Sequence[str], None] = 'effc208c0d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credential', 'secret_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credential', 'secret_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
