"""wiped DB and changed everything important to nullable false

Revision ID: fe063159fbdf
Revises: 0e310c54aa19
Create Date: 2025-10-06 13:00:49.831649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe063159fbdf'
down_revision: Union[str, Sequence[str], None] = '0e310c54aa19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secret', 'encrypted_secret_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('secret', 'secret_key_iv',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('secret', 'secret_iv',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'otp_secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'user_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'salt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'iv',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'iv',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'salt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'user_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'otp_secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('secret', 'secret_iv',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('secret', 'secret_key_iv',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('secret', 'encrypted_secret_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
