"""added user,vault and secret key to tables12

Revision ID: 199ee93d891a
Revises: 7a782019867a
Create Date: 2025-09-10 07:40:50.026792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199ee93d891a'
down_revision: Union[str, Sequence[str], None] = '7a782019867a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret', sa.Column('secret_key', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('user_key', sa.LargeBinary(), nullable=True))
    op.add_column('vault', sa.Column('vault_key', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault', 'vault_key')
    op.drop_column('user', 'user_key')
    op.drop_column('secret', 'secret_key')
    # ### end Alembic commands ###
