""" removed unique constraint from vualt model

Revision ID: 3592d7cd58ee
Revises: 33e8230ed8b3
Create Date: 2025-09-13 12:41:21.033924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3592d7cd58ee'
down_revision: Union[str, Sequence[str], None] = '33e8230ed8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
