"""removed vault key, added user salt

Revision ID: 4a9f08b0b30d
Revises: 199ee93d891a
Create Date: 2025-09-11 07:39:51.647236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a9f08b0b30d'
down_revision: Union[str, Sequence[str], None] = '199ee93d891a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.String(), nullable=True))
    op.drop_column('vault', 'vault_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault', sa.Column('vault_key', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###
