"""added user,vault and secret key to tables

Revision ID: 7a782019867a
Revises: 91d9bf144ef0
Create Date: 2025-09-10 07:38:37.938716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a782019867a'
down_revision: Union[str, Sequence[str], None] = '91d9bf144ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret', sa.Column('secret_key', sa.LargeBinary(), nullable=False))
    op.add_column('user', sa.Column('user_key', sa.LargeBinary(), nullable=False))
    op.add_column('vault', sa.Column('vault_key', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault', 'vault_key')
    op.drop_column('user', 'user_key')
    op.drop_column('secret', 'secret_key')
    # ### end Alembic commands ###
