""" secret: added secret key iv and secret data iv

Revision ID: 83780a9b0b2a
Revises: 6f0cb4e18e9e
Create Date: 2025-09-13 11:35:09.839139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83780a9b0b2a'
down_revision: Union[str, Sequence[str], None] = '6f0cb4e18e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret', sa.Column('encrypted_secret_key', sa.String(), nullable=True))
    op.add_column('secret', sa.Column('secret_key_iv', sa.String(), nullable=True))
    op.add_column('secret', sa.Column('secret_iv', sa.String(), nullable=True))
    op.drop_column('secret', 'secret_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret', sa.Column('secret_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('secret', 'secret_iv')
    op.drop_column('secret', 'secret_key_iv')
    op.drop_column('secret', 'encrypted_secret_key')
    # ### end Alembic commands ###
