"""added iv for AES

Revision ID: fba1a3348d98
Revises: f3a5b4fcc65c
Create Date: 2025-09-12 07:52:23.302035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba1a3348d98'
down_revision: Union[str, Sequence[str], None] = 'f3a5b4fcc65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('iv', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'iv')
    # ### end Alembic commands ###
